# menu
menu:
  Home: .
  Archives: archives  # 归档
  Categories: categories  # 分类
  Tags: tags  # 标签
  Repository: repository  # github repositories
  Books: books  # 豆瓣书单
  Links: links  # 友链
  About: about  # 关于
  
 
language: zh-CN

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
  tags: icon-tags
  repository: icon-project
  books: icon-book-fill
  links: icon-friendship
  about: icon-cup-fill

# rss
rss: /atom.xml

# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: ../images/logo.png
  title: Luler的博客 # 页面title
  favicon: /favicon.png
  board: <p>欢迎交流与分享经验!</p> # 站点公告
  copyright: true # 底部版权信息

# config
config:
  skin: theme-black # 主题颜色 theme-black theme-blue theme-green theme-purple
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: true # 是否开启当前菜单高亮显示
  thumbnail: false # enable posts thumbnail, options: true, false
  excerpt_link: Read More

# Pagination
pagination:
  number: false
  prev: 
    alwayShow: true
  next:
    alwayShow: true

# Sidebar
title: 文章标题
categories: 文章分类
tags: 文章标签

sidebar: right
widgets:
  - board  
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive  

# widget behavior
archive_type: 'monthly'
show_count: true

# Fancybox
fancybox: false

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  baidu: false # you need to disable other search engines to use Baidu search

# Donate
donate:
  enable: true
  # 微信打赏
  wechatpay:
    qrcode: images/weixin.jpg
    title: 微信支付
  # 支付宝打赏
  alipay: 
    qrcode: images/zhifubao.jpg
    title: 支付宝

# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: true  # 是否启用分享
  sites: weibo,qq,wechat,facebook,twitter  # PC端显示的分享图标
  mobile_sites: weibo,qq,qzone  # 移动端显示的分享图标

# Github
github: 
  username: Lulerx  # github username

# Comment
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
comment:
  type: valine  # 启用哪种评论系统 集成了disqus、友言、来必力、gitment、gitalk评论系统，选择其中一种即可
  disqus:  # enter disqus shortname here
  youyan: 
    uid:  # enter youyan uid 
  livere:
    uid: # enter youyan uid 
  gitment:
    githubID: 
    repo: 
    ClientID: 
    ClientSecret: 
    lazy: false
  gitalk: # gitalk. https://gitalk.github.io/
    owner:  #必须. GitHub repository 所有者，可以是个人或者组织。
    admin:  #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
    repo:  #必须. GitHub repository.
    ClientID:  #必须. GitHub Application Client ID.
    ClientSecret:  #必须. GitHub Application Client Secret.
  valine: # Valine官方地址: https://valine.js.org
    appid: 9qzcCSNQltNOliRHEXrKlgeR-gzGzoHsz  # 你的 leancloud 应用 appid
    appkey: Ei4uB8XqNBYgQ87K0rjwQMsq  # 你的 leancloud 应用 appkey
    notify: false # 是否开始评论邮件提醒, 教程: https://github.com/xCss/Valine/wiki
    verify: false # 是否开始验证码功能, 开始邮件提醒会自动开启验证码功能
    placeholder: 说点什么... # 输入框默认内容
    avatar: mp # 头像展示方式, 具体设置项教程: https://valine.js.org/configuration.html#avatar
    meta: nick,mail,link # 自定义评论信息
    pageSize: 10 # 评论列表分页
    lang: zh-cn, # 多语言支持 zh-cn | en
    visitor: true # 文章阅读量统计:  https://valine.js.org/visitor.html
    highlight: true # 代码高亮
    recordIP: true # 记录评论者的IP

# douban 豆瓣书单
# Api：
  # https://developers.douban.com/wiki/?title=book_v2 图书
  # https://developers.douban.com/wiki/?title=movie_v2 电影
# books：  
  # https://api.douban.com/v2/book/user/:name/collections?start=0&count=100 个人书单列表
# movies: 
  # https://api.douban.com/v2/movie/in_theaters 正在上映的电影
  # https://api.douban.com/v2/movie/coming_soon 即将上映的电影
  # https://api.douban.com/v2/movie/subject/:id 单个电影信息
  # https://api.douban.com/v2/movie/search?q={text} 电影搜索
douban:
  user: # 豆瓣用户名
  start: 0 # 从哪一条记录开始
  count: 100 # 获取豆瓣书单数据条数
  
# PV
pv:
  busuanzi:
    enable: true  # 不蒜子统计
  leancloud:
    enable: false  # leancloud统计
    app_id: # leancloud <AppID>
    app_key: # leancloud <AppKey>
        
# wordcount
postCount:
  enable: false
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计 

# Plugins
plugins:
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key
  tencent_analytics: 
  
# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:  
  
# profile
profile:
  enabled: true # Whether to show profile bar
  avatar: images/touxiang.jpg
  gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: Luler
  author_title: Web Developer & Designer
  author_description: 个人简介。
  location: Chengdu, China
  follow: 
  # Social Links
  social:
    links:
      github: https://github.com/Lulerx
      weibo: #http://weibo.com/Lulerx
      #twitter: #https://twitter.com/Lulerx
      # facebook: /
      # dribbble: /
      #behance: #https://www.behance.net/Lulerx
      zhihu: #http://weibo.com/Lulerx
      rss: atom.xml
    link_tooltip: true # enable the social link tooltip, options: true, false
  # My Skills 
  # 技能列表
  skills:
    java: ★★★★☆
    Springboot: ★★★★☆
    Javascript: ★★★☆☆
    HTML+CSS: ★★★☆☆
    VUE: ★★★☆☆
    Git: ★★☆☆☆
    
  # My Personal Links
  # 个人链接
  links:
    Github: https://github.com/Lulerx
    #Blog: http://blog.cofess.com
    微博: http://weibo.com/
    #花瓣: http://huaban.com/cofess
    #Behance: https://www.behance.net/cofess
  # My Personal Labels
  # 个人标签
  labels:
    - 后端
    - java开发
    - java web
  # My Personal Works
  works:
    name:
      link: http://www.example.com
      date: 2020
  # My Personal Projects
  projects:
    cofess/gulp-startpro: https://github.com/cofess/gulp-startpro
    cofess/hexo-theme-pure: https://github.com/cofess/hexo-theme-pure
    
    
# hexo-neat
neat_enable: true
neat_html:
  enable: true
  exclude:  
neat_css:
  enable: true
  exclude:
    - '*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js' 